# action.yml
name: 'OWASP Dependency Track check'
description: 'Creates BoM and upload repository to OWASP Dependency Track to find vulnerabilities'
branding:
  icon: 'check-square'  
  color: 'green'

inputs:
  url:  
    description: 'URL of OWASP Dependency Track REST API'
    required: true
    default: 'https://dtrack.quobis.com/'
  key:
    description: 'Key to access OWASP Dependency Track REST API'
    required: true
    default: 'USEAVALIDKEY'
  language:
    description: 'Programming language'
    required: true
    default: 'nodejs'
  project-name:
    description: 'Project name to report to Dependency Track. Falls back to the git repository name when not specified.'
    required: false
    default: ''
  project-version:
    description: 'Project version number to report to Dependency Track. Falls back to the git ref when not specified.'
    required: false
    default: ''
  working-directory:
    description: 'The working directory to use for resolving paths for lockfiles.'
    required: false
    default: ''

outputs:
  riskscore:
    description: 'String with the number of vulnerabilities found'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.key }}
    - ${{ inputs.language }}
    - ${{ inputs.working-directory }}
    - ${{ inputs.project-name }}
    - ${{ inputs.project-version }}
